// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Mark struct {
	ID        string
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Product struct {
	ID        string
	Name      string
	Price     float64
	MarkID    sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type User struct {
	ID        string
	Name      string
	Email     string
	Password  string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
